### ISSUE TITLE
[CSS]  text 넘어가는 ...처리 text-overflow: elipcis

### ISSUE THREAD

**Issue by amorfati0310** [amorfati0310/TipBooks#6]
```scss
//ex) 4줄짜리 
   &__description {
 font-size: 15px;
        line-height: 23px;
        color: $gray-800;
        height: 92px;
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 4;
        -webkit-box-orient: vertical;
        word-wrap: break-word;
        margin: 0;
        &--isExpanded {
            height: auto;
            text-overflow: unset;
            display: flex;
            overflow: inherit;
        }
}
```
